# Install the basic repositories
class yum::centos {
  if versioncmp($facts['os']['release']['major'],'8') < 0 {
    $epel_suffix = "-${facts['os']['release']['major']}"
    $repos = {
      'base' => {
        descr          => 'CentOS-$releasever - Base',
        mirrorlist     => 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os',
        enabled        => 1,
        gpgcheck       => 1,
        repo_gpgcheck  => 1,
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-${facts['os']['release']['major']}",
        manage_gpgkey  => false,
        priority       => 1,
      },
      'debuginfo' => {
        descr          => 'CentOS-$releasever - DebugInfo',
        mirrorlist     => 'http://debuginfo.centos.org/$releasever/$basearch/',
        enabled        => 0,
        gpgcheck       => 1,
        repo_gpgcheck  => 0,
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Debug-${facts['os']['release']['major']}",
        manage_gpgkey  => true,
        priority       => 1,
      },
      'updates' => {
        descr          => 'CentOS-$releasever - Updates',
        mirrorlist     => 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates',
        enabled        => 1,
        gpgcheck       => 1,
        repo_gpgcheck  => 1,
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-${facts['os']['release']['major']}",
        manage_gpgkey  => false,
        priority       => 1,
      },
      'extras' => {
        descr          => 'CentOS-$releasever - Extras',
        mirrorlist     => 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras',
        enabled        => 1,
        gpgcheck       => 1,
        repo_gpgcheck  => 1,
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-${facts['os']['release']['major']}",
        manage_gpgkey  => false,
        priority       => 1,
      },
      'centosplus' => {
        descr          => 'CentOS-$releasever - Centosplus',
        mirrorlist     => 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus',
        enabled        => 1,
        gpgcheck       => 1,
        repo_gpgcheck  => 1,
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-${facts['os']['release']['major']}",
        manage_gpgkey  => false,
        priority       => 2,
      },
      "centos${facts['os']['release']['major']}-plus"   => {
        descr          => 'CentOS-$releasever - Plus',
        mirrorlist     => 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus',
        enabled        => 1,
        gpgcheck       => 1,
        repo_gpgcheck  => 1,
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-${facts['os']['release']['major']}",
        priority       => 15,
      },
      'epel'           => {
        descr          => 'Extra Packages for Enterprise Linux $releasever - $basearch',
        metalink       => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-7&arch=$basearch&infra=$infra&content=$contentdir',
        enabled        => 1,
        gpgcheck       => 1,
        failovermethod => 'priority',
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL${epel_suffix}",
        priority       => 16,
      },
      'epel-debuginfo' => {
        descr          => 'Extra Packages for Enterprise Linux $releasever - $basearch - Debug',
        metalink       => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-debug-7&arch=$basearch&infra=$infra&content=$contentdir',
        enabled        => 0,
        gpgcheck       => 1,
        failovermethod => 'priority',
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL${epel_suffix}",
        priority       => 16,
      },
      'epel-source' => {
        descr          => 'Extra Packages for Enterprise Linux $releasever - $basearch - Source',
        metalink       => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-source-7&arch=$basearch&infra=$infra&content=$contentdir',
        enabled        => 0,
        gpgcheck       => 1,
        failovermethod => 'priority',
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL${epel_suffix}",
        priority       => 16,
      },
      'epel-testing'   => {
        descr          => 'Extra Packages for Enterprise Linux $releasever - Testing - $basearch',
        metalink       => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-epel7&arch=$basearch&infra=$infra&content=$contentdir',
        enabled        => 0,
        gpgcheck       => 1,
        failovermethod => 'priority',
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL${epel_suffix}",
        priority       => 16,
      },
      'epel-testing-debuginfo' => {
        descr          => 'Extra Packages for Enterprise Linux $releasever - Testing - $basearch - Debug',
        metalink       => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-debug-epel7&arch=$basearch&infra=$infra&content=$contentdir',
        enabled        => 0,
        gpgcheck       => 1,
        failovermethod => 'priority',
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL${epel_suffix}",
        priority       => 16,
      },
      'epel-testing-source' => {
        descr          => 'Extra Packages for Enterprise Linux $releasever - Testing - $basearch - Source',
        metalink       => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-source-epel7&arch=$basearch&infra=$infra&content=$contentdir',
        enabled        => 0,
        gpgcheck       => 1,
        failovermethod => priority,
        gpgkey         => "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL${epel_suffix}",
        priority       => 16,
      },
      'elrepo' => {
        descr      => 'ELRepo.org Community Enterprise Linux Repository - el$releasever',
        baseurl    => 'http://elrepo.org/linux/elrepo/el$relesever/$basearch/',
        mirrorlist => 'http://elrepo.org/mirrors-elrepo.el$releasever',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org',
        priority   => 20,
      },
      'elrepo-testing' => {
        descr      => 'ELRepo.org Community Enterprise Linux Testing Repository - el$releasever',
        baseurl    => 'http://elrepo.org/linux/testing/el$releasever/$basearch/',
        mirrorlist => 'http://elrepo.org/mirrors-elrepo-testing.el$releasever',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org',
        priority   => 20,
      },

      'elrepo-kernel' => {
        descr      => 'ELRepo.org Community Enterprise Linux Kernel Repository - el$releasever',
        baseurl    => 'http://elrepo.org/linux/kernel/el$releasever/$basearch/',
        mirrorlist => 'http://elrepo.org/mirrors-elrepo-kernel.el$releasever',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org',
        priority   => 20,
      },

      'elrepo-extras' => {
        descr      => 'ELRepo.org Community Enterprise Linux Repository - el$releasever',
        baseurl    => 'http://elrepo.org/linux/extras/el$releasever/$basearch/',
        mirrorlist => 'http://elrepo.org/mirrors-elrepo-extras.el$releasever',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org',
        priority   => 20,
      },
      'nux-dextop' => {
        descr    => 'Nux.Ro RPMs for general desktop use',
        baseurl  => 'http://li.nux.ro/download/nux/dextop/el$releasever/$basearch/ http://mirror.li.nux.ro/li.nux.ro/nux/dextop/el$releasever/$basearch/',
        enabled  => 1,
        gpgcheck => 1,
        gpgkeyid => '85C6CD8A',
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-nux.ro',
        protect  => 0,
        priority => 30,
      },
      'nux-dextop-testing' => {
        descr    => 'Nux.Ro RPMs for general desktop use - testing',
        baseurl  => 'http://li.nux.ro/download/nux/dextop-testing/el$releasever/$basearch/',
        enabled  => 0,
        gpgcheck => 1,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-nux.ro',
        protect  => 0,
        priority => 30,
      },
    }
  } elsif versioncmp($facts['os']['release']['major'],'8') == 0 {
    $repos = {
      'AppStream'                      => {
        descr         => 'CentOS-$releasever - AppStream',
        mirrorlist    => 'http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=AppStream&infra=$infra',
        gpgcheck      => 1,
        repo_gpgcheck => 1,
        enabled       => 1,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority      => 1,
      },
      'BaseOS'                         => {
        descr         => 'CentOS-$releasever - Base',
        mirrorlist    => 'http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=BaseOS&infra=$infra',
        gpgcheck      => 1,
        repo_gpgcheck => 1,
        enabled       => 1,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority      => 1,
      },
      'base-debuginfo'                 => {
        descr         => 'CentOS-$releasever - Debuginfo',
        baseurl       => 'http://debuginfo.centos.org/$stream/$basearch/',
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        enabled       => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority      => 1,
      },
      'extras'                         => {
        descr         => 'CentOS-$releasever - Extras',
        mirrorlist    => 'http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=extras&infra=$infra',
        gpgcheck      => 1,
        repo_gpgcheck => 1,
        enabled       => 1,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority      => 1,
      },
      'HighAvailability'               => {
        descr         => 'CentOS-$releasever - HA',
        mirrorlist    => 'http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=extras&infra=$infra',
        gpgcheck      => 1,
        repo_gpgcheck => 1,
        enabled       => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority      => 1,
      },
      'PowerTools'                     => {
        descr         => 'CentOS-$releasever - PowerTools',
        mirrorlist    => 'http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=PowerTools&infra=$infra',
        gpgcheck      => 1,
        repo_gpgcheck => 1,
        enabled       => 1,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority      => 1,
      },
      'epel'                           => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - $basearch',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 1,
        gpgcheck => 1,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        priority => 16,
      },
      'epel-debuginfo'                 => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - $basearch - Debug',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-debug-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-source'                    => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - $basearch - Source',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-source-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-testing'                   => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Testing - $basearch',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-epel$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgcheck => 1,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        priority => 16,
      },
      'epel-testing-debuginfo'         => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Testing - $basearch - Debug',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-debug-epel$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-testing-source'            => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Testing - $basearch - Source',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-source-epel$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-next' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next - $basearch',
        metalink => 'https://mirrors.fedoraproject.org/metalink?repo=epel-next-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 1,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-next-debuginfo' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next - $basearch - Debug',
        metalink => 'https://mirrors.fedoraproject.org/metalink?repo=epel-next-debug-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-next-source' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next - $basearch - Source',
        metalink => 'https://mirrors.fedoraproject.org/metalink?repo=epel-next-source-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-next-testing' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next - Testing - $basearch',
        metalink => 'https://mirrors.fedoraproject.org/metalink?repo=epel-testing-next-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-next-testing-debuginfo' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next - Testing - $basearch - Debug',
        metalink => 'https://mirrors.fedoraproject.org/metalink?repo=epel-testing-next-debug-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-next-testing-source' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next - Testing - $basearch - Source',
        metalink => 'https://mirrors.fedoraproject.org/metalink?repo=epel-testing-next-source-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8',
        gpgcheck => 1,
        priority => 16,
      },
      'rpmfusion-free-updates' => {
        descr      => 'RPM Fusion for EL 8 - Free - Updates',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=free-el-updates-released-8&arch=$basearch',
        enabled    => 1,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-8',
        priority   => 30,
      },
      'rpmfusion-free-updates-debuginfo' => {
        descr      => 'RPM Fusion for EL 8 - Free - Updates Debug',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=free-el-updates-released-debug-8&arch=$basearch',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-8',
        priority   => 30,
      },
      'rpmfusion-free-updates-source' => {
        descr      => 'RPM Fusion for EL 8 - Free - Updates Source',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=free-el-updates-released-source-8&arch=$basearch',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-8',
        priority   => 30,
      },
      'rpmfusion-free-updates-testing' => {
        descr      => 'RPM Fusion for EL 8 - Free - Test Updates',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=free-el-updates-testing-8&arch=$basearch',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-8',
        priority   => 30,
      },
      'rpmfusion-free-updates-testing-debuginfo' => {
        descr      => 'RPM Fusion for EL 8 - Free - Updates Debug',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=free-el-updates-testing-debug-8&arch=$basearch',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-8',
        priority   => 30,
      },
      'rpmfusion-free-updates-testing-source' => {
        descr      => 'RPM Fusion for EL 8 - Free - Updates Source',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=free-el-updates-testing-source-8&arch=$basearch',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-8',
        priority   => 30,
      },
      'rpmfusion-nonfree-updates' => {
        descr      => 'RPM Fusion for EL 8 - Nonree - Updates',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=nonfree-el-updates-released-8&arch=$basearch',
        enabled    => 1,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-8',
        priority   => 30,
      },
      'rpmfusion-nonfree-updates-debuginfo' => {
        descr      => 'RPM Fusion for EL 8 - Free - Updates Debug',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=nonfree-el-updates-released-debug-8&arch=$basearch',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-8',
        priority   => 30,
      },
      'rpmfusion-nonfree-updates-source' => {
        descr      => 'RPM Fusion for EL 8 - Free - Updates Source',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=nonfree-el-updates-released-source-8&arch=$basearch',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-8',
        priority   => 30,
      },
      'rpmfusion-nonfree-updates-testing' => {
        descr      => 'RPM Fusion for EL 8 - Free - Test Updates',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=nonfree-el-updates-testing-8&arch=$basearch',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-8',
        priority   => 30,
      },
      'rpmfusion-nonfree-updates-testing-debuginfo' => {
        descr      => 'RPM Fusion for EL 8 - Free - Updates Debug',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=nonfree-el-updates-testing-debug-8&arch=$basearch',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-8',
        priority   => 30,
      },
      'rpmfusion-nonfree-updates-testing-source' => {
        descr      => 'RPM Fusion for EL 8 - Free - Updates Source',
        mirrorlist => 'http://mirrors.rpmfusion.org/mirrorlist?repo=nonfree-el-updates-testing-source-8&arch=$basearch',
        enabled    => 0,
        gpgcheck   => 1,
        gpgkey     => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-8',
        priority   => 30,
      },
    }
    package { [
      'epel-release',
      'epel-next-release',
      'rpmfusion-free-release',
      'rpmfusion-nonfree-release',]:
      ensure  => installed,
      require => Yum::Repo['epel','rpmfusion-free-updates','rpmfusion-nonfree-updates'],
    }
  } elsif versioncmp($facts['os']['release']['major'],'9') == 0 {
    $repos = {
      'baseos' => {
        descr           => 'CentOS-$releasever - BaseOS',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-baseos-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 1,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'baseos-debug' => {
        descr           => 'CentOS-$releasever - BaseOS - Debug',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-baseos-debug-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'baseos-source' => {
        descr           => 'CentOS-$releasever - BaseOS - Source',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-baseos-source-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'appstream' => {
        descr           => 'CentOS-$releasever - AppStream',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-appstream-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 1,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'appstream-debug' => {
        descr           => 'CentOS-$releasever - AppStream - Debug',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-appstream-debug-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'appstream-source' => {
        descr           => 'CentOS-$releasever - AppStream - Source',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-appstream-source-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'crb' => {
        descr           => 'CentOS-$releasever - CRB',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-crb-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 1,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'crb-debug' => {
        descr           => 'CentOS-$releasever - CRB - Debug',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-crb-debug-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'crb-source' => {
        descr           => 'CentOS-$releasever - CRB - Source',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-crb-source-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'extras-common' => {
        descr           => 'CentOS-$releasever - Extras packages',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-extras-sig-extras-common-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 1,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Extras-SHA512',
        priority        => 1,
        metadata_expire => '6h',
      },
      'extras-common-source' => {
        descr           => 'CentOS-$releasever - Extras packages - source',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-extras-sig-extras-common-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Extras-SHA512',
        priority        => 1,
        metadata_expire => '6h',
      },
      'highavailability' => {
        descr           => 'CentOS-$releasever - HighAvailability',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-highavailability-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'highavailability-debug' => {
        descr           => 'CentOS-$releasever - HighAvailability - Debug',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-highavailability-debug-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'highavailability-source' => {
        descr           => 'CentOS-$releasever - HighAvailability - Source',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-highavailability-source-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'nfv' => {
        descr           => 'CentOS-$releasever - NFV',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-nfv-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'nfv-debug' => {
        descr           => 'CentOS-$releasever - NFV - Debug',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-nfv-debug-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'nfv-source' => {
        descr           => 'CentOS-$releasever - NFV - Source',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-nfv-source-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'rt' => {
        descr           => 'CentOS-$releasever - RT',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-rt-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'rt-debug' => {
        descr           => 'CentOS-$releasever - RT - Debug',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-rt-debug-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'rt-source' => {
        descr           => 'CentOS-$releasever - RT - Source',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-rt-source-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'resilientstorage' => {
        descr           => 'CentOS-$releasever - ResilientStorage',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-resilientstorage-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'resilientstorage-debug' => {
        descr           => 'CentOS-$releasever - ResilientStorage - Debug',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-resilientstorage-debug-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'resilientstorage-source' => {
        descr           => 'CentOS-$releasever - ResilientStorage - Source',
        metalink        => 'https://mirrors.centos.org/metalink?repo=centos-resilientstorage-source-$stream&arch=$basearch&protocol=https',
        gpgcheck        => 1,
        repo_gpgcheck   => 1,
        enabled         => 0,
        gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial',
        priority        => 1,
        metadata_expire => '6h',
      },
      'epel' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - $basearch',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 1,
        gpgcheck => 1,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        priority => 16,
      },
      'epel-debuginfo' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - $basearch - Debug',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-debug-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-source' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - $basearch - Source',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-source-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-testing' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Testing - $basearch',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-epel$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgcheck => 1,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        priority => 16,
      },
      'epel-testing-debuginfo' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Testing - $basearch - Debug',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-debug-epel$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-testing-source' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Testing - $basearch - Source',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-source-epel$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-next' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next- $basearch',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-next-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 1,
        gpgcheck => 1,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        priority => 16,
      },
      'epel-next-debuginfo' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next- $basearch - Debug',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-next-debug-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-next-source' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next- $basearch - Source',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=epel-next-source-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-next-testing' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next- Testing - $basearch',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-epel-next$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgcheck => 1,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        priority => 16,
      },
      'epel-next-testing-debuginfo' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next- Testing - $basearch - Debug',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-debug-epel-next$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        gpgcheck => 1,
        priority => 16,
      },
      'epel-next-testing-source' => {
        descr    => 'Extra Packages for Enterprise Linux $releasever - Next - Testing - $basearch - Source',
        metalink => 'https://mirrors.fedoraproject.org/metalink?protocol=https&repo=testing-source-epel-next$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        enabled  => 0,
        gpgkey   => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9',
        gpgcheck => 1,
        priority => 16,
      },
      'rpmfusion-free-updates' => {
        descr         => 'RPM Fusion for EL 9 - Free - Updates',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=free-el-updates-released-9&arch=$basearch',
        enabled       =>1,
        gpgcheck      =>1,
        repo_gpgcheck =>0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-9',
        priority      => 10,
      },
      'rpmfusion-free-updates-debuginfo' => {
        descr         => 'RPM Fusion for EL 9 - Free - Updates Debug',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=free-el-updates-released-debug-9&arch=$basearch',
        enabled       => 0,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-9',
      },
      'rpmfusion-free-updates-source' => {
        descr         => 'RPM Fusion for EL 9 - Free - Updates Source',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=free-el-updates-released-source-9&arch=$basearch',
        enabled       => 0,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-9',
      },
      'rpmfusion-free-updates-testing' => {
        descr         => 'RPM Fusion for EL 9 - Free - Test Updates',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=free-el-updates-testing-9&arch=$basearch',
        enabled       => 0,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-9',
      },
      'rpmfusion-free-updates-testing-debuginfo' => {
        descr         => 'RPM Fusion for EL 9 - Free - Test Updates Debug',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=free-el-updates-testing-debug-9&arch=$basearch',
        enabled       => 0,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-9',
      },
      'rpmfusion-free-updates-testing-source' => {
        descr         => 'RPM Fusion for EL 9 - Free - Test Updates Source',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=free-el-updates-testing-source-9&arch=$basearch',
        enabled       => 0,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-9',
      },
      'rpmfusion-nonfree-updates' => {
        descr         => 'RPM Fusion for EL 9 - Nonfree - Updates',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=nonfree-el-updates-released-9&arch=$basearch',
        enabled       => 1,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-9',
      },
      'rpmfusion-nonfree-updates-debuginfo' => {
        descr         => 'RPM Fusion for EL 9 - Nonfree - Updates Debug',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=nonfree-el-updates-released-debug-9&arch=$basearch',
        enabled       => 0,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-9',
      },
      'rpmfusion-nonfree-updates-source' => {
        descr         => 'RPM Fusion for EL 9 - Nonfree - Updates Source',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=nonfree-el-updates-released-source-9&arch=$basearch',
        enabled       => 0,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-9',
      },
      'rpmfusion-nonfree-updates-testing' => {
        descr         => 'RPM Fusion for EL 9 - Nonfree - Test Updates',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=nonfree-el-updates-testing-9&arch=$basearch',
        enabled       => 0,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-9',
      },
      'rpmfusion-nonfree-updates-testing-debuginfo' => {
        descr         => 'RPM Fusion for EL 9 - Nonfree - Test Updates Debug',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=nonfree-el-updates-testing-debug-9&arch=$basearch',
        enabled       => 0,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-9',
      },
      'rpmfusion-nonfree-updates-testing-source' => {
        descr         => 'RPM Fusion for EL 9 - Nonfree - Test Updates Source',
        metalink      => 'https://mirrors.rpmfusion.org/metalink?repo=nonfree-el-updates-testing-source-9&arch=$basearch',
        enabled       => 0,
        #type=rpm-md
        gpgcheck      => 1,
        repo_gpgcheck => 0,
        gpgkey        => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-9',
      }
    }
    package { [
      'epel-release',
      'epel-next-release',
      'rpmfusion-free-release',
      'rpmfusion-nonfree-release',]:
      ensure  => installed,
      require => Yum::Repo['epel','epel-next','rpmfusion-free-updates','rpmfusion-nonfree-updates'];
    }
  } else {
    fail "CentOS ${facts['os']['release']['major']} is not yet supported by this module"
  }
}
